### ISSUE TITLE
iOS Demo 报错

### ISSUE THREAD

**Issue by liuyang2211** [Tencent-RTC/TUIRoomKit#498]
Multiple commands produce '/Users/xxx/Library/Developer/Xcode/DerivedData/DemoApp-bcklqltkvultodgdcijkinogsdgo/Build/Products/Debug-iphonesimulator/DemoApp.app/Frameworks/ImSDK_Plus.framework'

![image](https://github.com/Tencent-RTC/TUIRoomKit/assets/19897206/ab21d4e2-15b4-4930-890a-0f5466973509)
![image](https://github.com/Tencent-RTC/TUIRoomKit/assets/19897206/8bbb936a-c8c5-4f9e-bbcc-bc5fd9e11ddb)

**Comment by Tangjianing123** [comment]
最新版本已经解决该问题。

**Comment by Tangjianing123** [comment]
已经解决，请用最新版本验证。
